name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
        
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/yuzhi-jiang/tools/piclivecode:latest
        docker push ghcr.io/yuzhi-jiang/tools/piclivecode:latest
      
